# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: springboot-init
  # 默认使用本地开发环境
  profiles:
    active: local
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # 敏感信息已移至 application-local.yml 文件
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/camp_circle}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:please_set_in_application_local_yml}
  # Redis 配置
  redis:
    database: ${REDIS_DATABASE:2}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:5000}
    password: ${REDIS_PASSWORD:}
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关配置
# 敏感信息已移至 application-local.yml 文件
wx:
  # 微信公众平台
  mp:
    token: ${WX_MP_TOKEN:please_set_in_application_local_yml}
    aesKey: ${WX_MP_AES_KEY:please_set_in_application_local_yml}
    appId: ${WX_MP_APP_ID:please_set_in_application_local_yml}
    secret: ${WX_MP_SECRET:please_set_in_application_local_yml}
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6379}
      type: Memory
  # 微信开放平台
  open:
    appId: ${WX_OPEN_APP_ID:please_set_in_application_local_yml}
    appSecret: ${WX_OPEN_APP_SECRET:please_set_in_application_local_yml}
  # 微信小程序
  miniapp:
    appId: ${WX_MINIAPP_APP_ID:please_set_in_application_local_yml}
    appSecret: ${WX_MINIAPP_APP_SECRET:please_set_in_application_local_yml}
# 对象存储配置
# 敏感信息已移至 application-local.yml 文件
cos:
  client:
    host: ${COS_HOST:please_set_in_application_local_yml}
    SecretId: ${COS_SECRET_ID:please_set_in_application_local_yml}
    SecretKey: ${COS_SECRET_KEY:please_set_in_application_local_yml}
    region: ${COS_REGION:ap-guangzhou}
    bucket: ${COS_BUCKET:please_set_in_application_local_yml}
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.caden.campcircle.controller
# JWT配置
# 敏感信息已移至 application-local.yml 文件
jwt:
  secret: ${JWT_SECRET:please_set_in_application_local_yml}

# RocketMQ 配置
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:campcircle-producer-group}
    send-message-timeout: ${ROCKETMQ_SEND_TIMEOUT:3000}
    retry-times-when-send-failed: ${ROCKETMQ_RETRY_TIMES:3}
  consumer:
    group: ${ROCKETMQ_CONSUMER_GROUP:campcircle-consumer-group}
