# 本地开发环境配置
# 此文件包含敏感信息，已在 .gitignore 中忽略，不会提交到远程仓库

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camp_circle
    username: root
    password: 123456
  
  # Redis 配置
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
    # password: your_redis_password_if_needed

# 微信相关配置
wx:
  # 微信公众平台
  mp:
    token: xxx
    aesKey: xxx
    appId: your_wx_mp_app_id
    secret: 998642e5d1d9dcea03a486ec486b07c7
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  
  # 微信开放平台
  open:
    appId: wx62fd590eb4cea404
    appSecret: 998642e5d1d9dcea03a486ec486b07c7
  
  # 微信小程序
  miniapp:
    appId: wx62fd590eb4cea404
    appSecret: 998642e5d1d9dcea03a486ec486b07c7

# 对象存储配置
cos:
  client:
    host: https://yun-picture-1253809168.cos.ap-guangzhou.myqcloud.com
    SecretId: AKIDgCYfbJadT7YljV3MRJxNYUSO8OVTQCvY
    SecretKey: WnqfLo24PWO3TffRyINDpDNJ0TiiU1KP
    region: ap-guangzhou
    bucket: yun-picture-1253809168

# JWT配置
jwt:
  secret: gsfsaddghIOHjiofjsafj989890dhfdiuijfsihifdsihmJJSPOkjd/.,fs/?09

# RocketMQ 配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: campcircle-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
  consumer:
    group: campcircle-consumer-group
